#ifndef VERSIONH_INCLUDED
#define VERSIONH_INCLUDED

#define PROJECT_NAME "SlideSensemaker"
#define PROJECT_VER  "1.1.0"
#define PROJECT_VER_MAJOR "1"
#define PROJECT_VER_MINOR "1"
#define PTOJECT_VER_PATCH "0"

#endif // VERSIONH_INCLUDED
