#pragma once

// ZERNIKE2D against the closed form (SPEC 4, oracle=analytic).
//
// The 30 magnitudes below are the Zernike moments of order <= 9 computed from the standard factorial
// series for the radial polynomial,
//
//     R_nm(r) = sum_k (-1)^k (n-k)! r^(n-2k) / ( k! ((n+m)/2-k)! ((n-m)/2-k)! )
//     A_nm    = (n+1)/pi * sum_pixels (I / sum I) * R_nm(r) * exp(-i m theta)
//
// evaluated on this family's fixture at the geometry ZernikeFeature uses: the unit disk centred on
// the ROI's intensity centroid with radius min(bbox width, bbox height). zernike.cpp evaluates R_nm
// through the Singh & Walia three-term recurrence instead, so this is an independent implementation
// of the same mathematics rather than a second copy of Nyxus' procedure - which is what makes the
// agreement a check and not a tautology (SPEC 5.2).
//
// Generated by tests/vetting/oracles/gen_zernike_analytic.py, which also cross-checks the same
// values against centrosome's own Zernike polynomials (a third implementation) and records why
// CellProfiler's MeasureObjectIntensityDistribution Zernikes are not comparable. Full account in
// tests/vetting/audit/zernike_2d_analytic_vetting_report.md.

#include <gtest/gtest.h>

#include "../src/nyx/featureset.h"        // Feature2D
#include "test_2d_zernike_common.h"       // calculate_zernike_2d_values;
                                          // <cmath> for std::fabs via test_main_nyxus.h
#include "test_ref_vals.h"                // ref_vals_map, <vector>

static const ref_vals_map<std::vector<double>> zernike_2d_analytic_ref_vals{
	{"ZERNIKE2D", {
		0.31830988618379069, 1.5814428522168366e-17, 0.71985225389069296,
		0.025780497111119398, 0.020669804576956489, 0.020090034548617464,
		0.62194689390734226, 0.08606870566116287, 0.0062425850646033931,
		0.082381409770710512, 0.093660754963766468, 0.0047976324379789192,
		0.17461460409333168, 0.12084127682551966, 0.031962211880315082,
		0.0025827535820692684, 0.14801658671869725, 0.21122543105565178,
		0.026366443634871319, 0.00080970804775625459, 0.24088546254504548,
		0.076966402148422861, 0.081733817517752869, 0.015377110253371636,
		0.00035143072544742133, 0.15309294756946509, 0.29425534815914156,
		0.069853801817987199, 0.0048691281137569972, 0.00010157413670881736,
	}},
};

// Measured residual against the closed form: worst 3.4e-15 relative, at (n=8,m=8). The band is
// rel=1e-12 -- three orders above the measurement, because the two implementations sum the same
// terms in different orders and the residual is float accumulation, not a method difference.
//
// This is ASSERT_NEAR with a computed band rather than the house agrees_gt, and the reason is entry
// 1. agrees_gt derives its tolerance as golden/frac, which cannot express an absolute floor -- at a
// golden of 1.5e-17 it would demand a match to ~1e-29. test_2d_zernike_regression.h uses the same
// shape at its own rel, so the family has one assertion idiom rather than two.
//
// The absolute floor is not padding: entry 1 is (n=1,m=1), the first moment about the intensity
// centroid the feature centres on, so it is a MATHEMATICAL ZERO. Both sides land at ~1.5e-17 and a
// purely relative band would compare two values at the noise floor. 1e-15 is well under every other
// magnitude in the table, the smallest of which is 1.0e-4.
static const double ZERNIKE_ANALYTIC_REL_TOL = 1e-12;
static const double ZERNIKE_ANALYTIC_ABS_FLOOR = 1e-15;

void test_2d_zernike_moments_analytic()
{
	std::vector<std::vector<double>> fvals;
	calculate_zernike_2d_values(fvals);

	const auto& actual = fvals[(int)Nyxus::Feature2D::ZERNIKE2D];
	const auto& golden = zernike_2d_analytic_ref_vals.at("ZERNIKE2D");
	ASSERT_EQ(actual.size(), golden.size()) << "ZERNIKE2D";

	for (size_t i = 0; i < golden.size(); i++)
		ASSERT_NEAR(actual[i], golden[i],
			std::fabs(golden[i]) * ZERNIKE_ANALYTIC_REL_TOL + ZERNIKE_ANALYTIC_ABS_FLOOR)
			<< "ZERNIKE2D[" << i << "]";
}
