"""Validate tests/vetting/oracle_coverage.csv and regenerate coverage_report.md. Stdlib only."""
import csv, os, sys, argparse

COLUMNS = ["dim","feature","family","status","oracle","agreement","config_recipe",
           "tolerance","current_test","target_test","candidate_oracle","flag","source","notes"]
ALLOWED_STATUS = {"vetted","regression","untested"}
ALLOWED_ORACLES = {"pyradiomics","radiomicsj","mirp","matlab","cellprofiler","mitk",
                   "feature2djava","wndcharm","imea","imagej","fraclac","ibsi","analytic","skimage"}

def load_registry(path):
    with open(path, newline="") as fh:
        return list(csv.DictReader(fh))

def validate_rows(rows):
    errs = []
    if rows:
        missing = [c for c in COLUMNS if c not in rows[0]]
        if missing:
            errs.append(f"missing columns: {missing}")
            return errs
    for r in rows:
        f = (r.get("feature") or ""); st = (r.get("status") or "").strip(); ora = (r.get("oracle") or "").strip()
        if st not in ALLOWED_STATUS:
            errs.append(f"{f}: bad status {st!r}")
        if ora and ora not in ALLOWED_ORACLES:
            errs.append(f"{f}: oracle token {ora!r} not in SPEC 4 allowed set")
        if st == "vetted" and not ora:
            errs.append(f"{f}: status=vetted but no oracle")
        if st != "vetted" and ora:
            errs.append(f"{f}: status={st} but has oracle {ora!r}")
    return errs

def coverage_stats(rows):
    fam = {}
    tot = dict(total=0, vetted=0, regression=0, untested=0)
    for r in rows:
        st = r["status"].strip()
        tot["total"] += 1; tot[st] = tot.get(st, 0) + 1
        f = fam.setdefault(r["family"], dict(total=0, vetted=0, regression=0, untested=0))
        f["total"] += 1; f[st] = f.get(st, 0) + 1
    return dict(total=tot["total"], vetted=tot["vetted"], regression=tot["regression"],
                untested=tot["untested"], by_family=fam)

def render_report(rows):
    s = coverage_stats(rows)
    pct = (100.0 * s["vetted"] / s["total"]) if s["total"] else 0.0
    lines = ["# Nyxus Oracle-Vetting Coverage", "",
             "_Generated by check_coverage.py from oracle_coverage.csv. Do not edit by hand._", "",
             f"Features vetted by >=1 oracle: {s['vetted']}/{s['total']} ({pct:.0f}%)",
             f"regression: {s['regression']}  untested: {s['untested']}", "",
             "| family | total | vetted | regression | untested |",
             "|---|---|---|---|---|"]
    for name in sorted(s["by_family"]):
        f = s["by_family"][name]
        lines.append(f"| {name} | {f['total']} | {f['vetted']} | {f['regression']} | {f['untested']} |")
    return "\n".join(lines) + "\n"

def drift_warnings(rows, tests_dir):
    warns = []
    for r in rows:
        tgt = (r.get("target_test") or "").strip()
        if tgt and not os.path.exists(os.path.join(tests_dir, tgt)):
            warns.append(f"{r.get('feature', '')}: target_test {tgt} not found in {tests_dir}")
    return warns

def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", default="tests/vetting/oracle_coverage.csv")
    ap.add_argument("--report", default="tests/vetting/coverage_report.md")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args(argv)
    rows = load_registry(a.registry)
    errs = validate_rows(rows)
    if a.check:
        for e in errs: print("ERROR:", e)
        return 1 if errs else 0
    if a.write:
        if errs:
            for e in errs: print("ERROR:", e)
            return 1
        with open(a.report, "w") as fh: fh.write(render_report(rows))
        print(f"wrote {a.report}")
        return 0
    ap.print_help(); return 0

if __name__ == "__main__":
    sys.exit(main())
