"""Validate tests/vetting/oracle_coverage.csv and regenerate coverage_report.md. Stdlib only."""
import csv, os, sys, argparse

COLUMNS = ["dim","feature","family","status","oracle","agreement","config_recipe",
           "tolerance","current_test","target_test","candidate_oracle","flag","source","notes",
           # SPEC 3: the assertion a row records is identified by the exact gtest case it runs
           # as and the benchmark it runs on. A row naming neither says a feature is covered
           # without saying by what, which is what the 3D NGLDM review asked to close.
           "test_name","benchmark"]
ALLOWED_STATUS = {"vetted","regression","untested"}
ALLOWED_ORACLES = {"pyradiomics","radiomicsj","mirp","matlab","cellprofiler","mitk",
                   "feature2djava","wndcharm","imea","imagej","fraclac","ibsi","analytic","skimage",
                   "pydicom","opencv"}

def load_registry(path):
    with open(path, newline="") as fh:
        return list(csv.DictReader(fh))

def benchmark_ids(path):
    """-> the ids defined in benchmarks.md, i.e. every '## `bench...`' or '## `name`' heading."""
    import re
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8", errors="replace") as fh:
        return set(re.findall(r"^##\s+`([^`]+)`", fh.read(), re.M))


def validate_benchmarks(rows, benchmarks_md):
    """A benchmark id that is not defined is a pointer to nothing (SPEC 6.3)."""
    defined = benchmark_ids(benchmarks_md)
    if defined is None:
        return [f"{benchmarks_md} is missing; SPEC 6.3 requires it once any row names a benchmark"] \
            if any((r.get("benchmark") or "").strip() for r in rows) else []
    errs = []
    for r in rows:
        b = (r.get("benchmark") or "").strip()
        if b and b not in defined:
            errs.append(f"{r.get('feature','')}: benchmark {b!r} is not defined in "
                        f"{os.path.basename(benchmarks_md)}")
    return errs


def validate_rows(rows):
    errs = []
    if rows:
        missing = [c for c in COLUMNS if c not in rows[0]]
        if missing:
            errs.append(f"missing columns: {missing}")
            return errs
    for r in rows:
        f = (r.get("feature") or ""); st = (r.get("status") or "").strip(); ora = (r.get("oracle") or "").strip()
        # A row with more fields than the header means an unquoted comma inside one of them: csv
        # collects the overflow under the None key, every field after the comma is shifted, and the
        # last one silently drops out of the table. 3ROBUST_MEAN sat like that with a
        # "[P10,P90]" candidate_oracle -- its notes had become its source and its notes were gone.
        if None in r:
            errs.append(f"{f}: {len(r[None])} field(s) past the last column - an unquoted comma "
                        f"shifts every field after it; quote the field")
        if any(v is None for v in r.values()):
            errs.append(f"{f}: fewer fields than columns - the row is truncated")
        if st not in ALLOWED_STATUS:
            errs.append(f"{f}: bad status {st!r}")
        if ora and ora not in ALLOWED_ORACLES:
            errs.append(f"{f}: oracle token {ora!r} not in SPEC 4 allowed set")
        if st == "vetted" and not ora:
            errs.append(f"{f}: status=vetted but no oracle")
        if st != "vetted" and ora:
            errs.append(f"{f}: status={st} but has oracle {ora!r}")
    return errs

def coverage_stats(rows):
    # The registry is one row per assertion, so several oracle rows may cover one feature. Roll up
    # by (dimension, feature) for the headline metric instead of counting assertion rows as features.
    rank = {"untested": 0, "regression": 1, "vetted": 2}
    features = {}
    for r in rows:
        key = (r["dim"], r["feature"])
        if key not in features or rank[r["status"].strip()] > rank[features[key]["status"].strip()]:
            features[key] = r

    fam = {}
    tot = dict(total=0, vetted=0, regression=0, untested=0)
    for r in features.values():
        st = r["status"].strip()
        tot["total"] += 1; tot[st] = tot.get(st, 0) + 1
        f = fam.setdefault(r["family"], dict(total=0, vetted=0, regression=0, untested=0))
        f["total"] += 1; f[st] = f.get(st, 0) + 1
    return dict(total=tot["total"], vetted=tot["vetted"], regression=tot["regression"],
                untested=tot["untested"], by_family=fam)

def render_report(rows):
    s = coverage_stats(rows)
    pct = (100.0 * s["vetted"] / s["total"]) if s["total"] else 0.0
    lines = ["# Nyxus Oracle-Vetting Coverage", "",
             "_Generated by check_coverage.py from oracle_coverage.csv. Do not edit by hand._", "",
             f"Features vetted by >=1 oracle: {s['vetted']}/{s['total']} ({pct:.0f}%)",
             f"regression: {s['regression']}  untested: {s['untested']}", "",
             "| family | total | vetted | regression | untested |",
             "|---|---|---|---|---|"]
    for name in sorted(s["by_family"]):
        f = s["by_family"][name]
        lines.append(f"| {name} | {f['total']} | {f['vetted']} | {f['regression']} | {f['untested']} |")
    return "\n".join(lines) + "\n"

def drift_warnings(rows, tests_dir):
    warns = []
    for r in rows:
        tgt = (r.get("target_test") or "").strip()
        if tgt and not os.path.exists(os.path.join(tests_dir, tgt)):
            warns.append(f"{r.get('feature', '')}: target_test {tgt} not found in {tests_dir}")
    return warns

def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", default="tests/vetting/oracle_coverage.csv")
    ap.add_argument("--report", default="tests/vetting/coverage_report.md")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args(argv)
    rows = load_registry(a.registry)
    errs = validate_rows(rows)
    errs += validate_benchmarks(rows, os.path.join(os.path.dirname(a.registry) or ".",
                                                   "benchmarks.md"))
    if a.check:
        for e in errs: print("ERROR:", e)
        return 1 if errs else 0
    if a.write:
        if errs:
            for e in errs: print("ERROR:", e)
            return 1
        # newline LF: text mode would emit CRLF on Windows, and LF is the repo standard
        with open(a.report, "w", newline="\n") as fh: fh.write(render_report(rows))
        print(f"wrote {a.report}")
        return 0
    ap.print_help(); return 0

if __name__ == "__main__":
    sys.exit(main())
