"""Python regression tests for --preserve-hu / preserve_hu on 3D NIfTI CT volumes.

Uses the synthetic NIfTI fixtures in tests/data/hounsfield (generated by make_nifti_fixtures.py):
ct3d_int16.nii is an 8x8x8 signed int16 volume with stored pixel(idx) = idx - 200 (idx 0..511),
so stored values run -200..311 and cross zero. Its header sets scl_slope=2, scl_inter=-1024, i.e.
true HU = 2*stored - 1024 (range -1424..-402). mask3d.nii is an all-ones ROI over the whole volume.

In preserve_hu mode the NiftiLoader rescales each voxel to true HU then offsets by floor(HU_min):
  u = round((2*stored - 1024) - (-1424)) = 2*stored + 400  -> offset domain 0..1022, mean 511.
The non-unit scl_slope makes the HU rescale observable: with the flag OFF the loader keeps the raw
signed values (shifted by the raw min), giving MAX 511 / MEAN 255.5 instead. These tests pin both
the scl_slope/scl_inter rescale and the offset-base wiring in the NIfTI loader path.
"""
import os
import pathlib
import pytest
import nyxus

DATA = pathlib.Path(__file__).resolve().parent.parent / "data" / "hounsfield"
INTEN = str(DATA / "ct3d_int16.nii")
MASK = str(DATA / "mask3d.nii")

pytestmark = pytest.mark.skipif(
    not (os.path.exists(INTEN) and os.path.exists(MASK)),
    reason="NIfTI Hounsfield fixtures not present (run tests/data/hounsfield/make_nifti_fixtures.py)",
)

FEATS = ["3MIN", "3MAX", "3MEAN", "3INTEGRATED_INTENSITY"]


def _featurize(preserve_hu):
    nyx = nyxus.Nyxus3D(FEATS, preserve_hu=preserve_hu)
    df = nyx.featurize_files([INTEN], [MASK], False)  # explicit whole-volume mask
    return {c: float(df[c].iloc[0]) for c in FEATS}


def test_preserve_hu_nifti_offset_domain_values():
    # HU rescale (slope 2, intercept -1024) then offset by floor(HU min): u = 2*stored + 400.
    # stored -200..311 -> u 0..1022, mean 511, sum 261632 over the 512 voxels.
    f = _featurize(True)
    assert f["3MIN"] == pytest.approx(0.0)
    assert f["3MAX"] == pytest.approx(1022.0)
    assert f["3MEAN"] == pytest.approx(511.0)
    assert f["3INTEGRATED_INTENSITY"] == pytest.approx(261632.0)


def test_preserve_hu_nifti_no_wraparound():
    # The negative signed int16 values must not wrap into billions on the unsigned cast.
    f = _featurize(True)
    assert 0.0 <= f["3MIN"] < f["3MAX"] < 1e6
    assert f["3MEAN"] < 1e6


def test_preserve_hu_nifti_applies_rescale():
    # With the flag off the loader keeps raw-stored (shifted) values and ignores scl_slope, so the
    # non-unit slope makes the two modes diverge: HU MAX 1022 vs raw-shift MAX 511.
    on = _featurize(True)
    off = _featurize(False)
    assert off["3MAX"] == pytest.approx(511.0)
    assert on["3MAX"] == pytest.approx(2.0 * off["3MAX"])
