"""Python regression tests for the --preserve-hu / preserve_hu CT-Hounsfield mode.

Uses the TIFF fixtures in tests/data/hounsfield (generated by make_fixtures.py):
ct_int16.tif is a signed int16 CT image with pixel(r,c) = -1024 + idx*8,
idx = r*16 + c (values -1024..1016, crossing 0). preserve_hu must be exercised
through the FILE loader (numpy input bypasses the load-time quantization), so
these use featurize_files.

In HU mode the loader maps value -> value - floor(min) = value + 1024 = idx*8, so
the offset-domain feature pixels are 0..2040 (MEAN 1020). Without it, the negative
int16 values wrap on the unsigned cast into billions.
"""
import os
import pathlib
import pytest
import nyxus

DATA = pathlib.Path(__file__).resolve().parent.parent / "data" / "hounsfield"
INTEN = str(DATA / "ct_int16.tif")
MASK = str(DATA / "mask.tif")

pytestmark = pytest.mark.skipif(
    not (os.path.exists(INTEN) and os.path.exists(MASK)),
    reason="Hounsfield TIFF fixtures not present (run tests/data/hounsfield/make_fixtures.py)",
)

FEATS = ["INTEGRATED_INTENSITY", "MEAN", "MAX", "MIN"]


def _featurize(preserve_hu):
    nyx = nyxus.Nyxus(FEATS, preserve_hu=preserve_hu)
    df = nyx.featurize_files([INTEN], [MASK], True)
    return {c: float(df[c].iloc[0]) for c in FEATS}


def test_preserve_hu_offset_domain_values():
    # Offset-domain: pixel(idx) = idx*8, idx 0..255 -> MIN 0, MAX 2040, MEAN 1020.
    f = _featurize(True)
    assert f["MIN"] == pytest.approx(0.0)
    assert f["MAX"] == pytest.approx(2040.0)
    assert f["MEAN"] == pytest.approx(1020.0)
    assert f["INTEGRATED_INTENSITY"] == pytest.approx(1020.0 * 256)


def test_preserve_hu_no_wraparound():
    # The whole point: negative CT values must not wrap into billions.
    f = _featurize(True)
    assert f["MIN"] < f["MAX"] < 1e6
    assert f["MEAN"] < 1e6


def test_preserve_hu_off_differs():
    # With the flag off the signed values wrap, so results differ hugely from HU mode.
    on = _featurize(True)
    off = _featurize(False)
    assert off["MEAN"] != pytest.approx(on["MEAN"])
    assert off["MEAN"] > 1e6   # wrapped
