"""OFFLINE golden generator for tests/test_2d_intensity_histogram_mirp.h (SPEC 6.4).

Runs MIRP's intensity-histogram family on the IBSI digital phantom and prints the golden table to
paste into the oracle test. Run offline; CI never invokes it - the reference tool is not a runtime
dependency.

    conda create -n nyxus_mirp -c conda-forge python=3.11 mirp numpy
    python tests/vetting/oracles/gen_intensity_histogram_mirp.py

Provenance to record at the pinned goldens: tool=mirp, version (printed by this script),
config=ih.ibsi_fbn (fixed bin number, 6 bins, IBSI mode), fixture=the IBSI phantom as
tests/test_data.h stores it, read through ibsi_phantom.py so there is one copy of the pixels.

MIRP works entirely in the discretised domain, so its features correspond to the Nyxus `_IDX`
family - the statistics over bin indices. The `_VAL` family (the same statistics carried back into
the intensity domain) has no MIRP counterpart and is vetted analytically instead; see
gen_intensity_histogram_analytic.py and the audit reports for the conventions involved.
"""
import json
import logging
from importlib import metadata

import numpy as np

# MIRP narrates at INFO into the same stream as the golden table, and configures its own logger
# during the run, so the level has to be suppressed globally rather than set on a logger
logging.disable(logging.INFO)
import mirp   # noqa: E402

from ibsi_phantom import phantom_slices   # noqa: E402

NBINS = 6   # IH_PHANTOM_NBINS in the C++ tests

# MIRP column (before the discretisation suffix) -> the Nyxus feature it covers
MIRP_TO_NYXUS = {
    "ih_mean":        "IH_MEAN_IDX",
    "ih_var":         "IH_VARIANCE_IDX",
    "ih_skew":        "IH_SKEWNESS_IDX",
    "ih_kurt":        "IH_EXCESS_KURTOSIS_IDX",
    "ih_median":      "IH_MEDIAN_IDX",
    "ih_min":         "IH_MINIMUM_IDX",
    "ih_p10":         "IH_P10_IDX",
    "ih_p90":         "IH_P90_IDX",
    "ih_max":         "IH_MAXIMUM_IDX",
    "ih_mode":        "IH_MODE_IDX",
    "ih_iqr":         "IH_INTERQUANTILE_RANGE_IDX",
    "ih_range":       "IH_RANGE_IDX",
    "ih_mad":         "IH_MEAN_ABSOLUTE_DEVIATION_IDX",
    "ih_rmad":        "IH_ROBUST_MEAN_ABSOLUTE_DEVIATION_IDX",
    "ih_medad":       "IH_MEDIAN_ABSOLUTE_DEVIATION_IDX",
    "ih_cov":         "IH_COEFFICIENT_OF_VARIATION_IDX",
    "ih_qcod":        "IH_QUANTILE_COEFFICIENT_OF_DISPERSION_IDX",
    "ih_entropy":     "IH_ENTROPY_IDX",
    "ih_uniformity":  "IH_UNIFORMITY_IDX",
    "ih_max_grad":    "IH_MAX_GRADIENT",
    "ih_max_grad_g":  "IH_MAX_GRADIENT_IDX",
    "ih_min_grad":    "IH_MIN_GRADIENT",
    "ih_min_grad_g":  "IH_MIN_GRADIENT_IDX",
}

SUFFIX = "_fbn_n%d" % NBINS


def run():
    slices = phantom_slices()
    volume = np.stack([a for a, _ in slices]).astype(float)
    mask = np.stack([m for _, m in slices])
    # by_slice=False: the Nyxus IH test builds one ROI out of all 4 slices, and the histogram is
    # over that whole voxel set
    res = mirp.extract_features(image=volume, mask=mask, by_slice=False,
                                base_discretisation_method="fixed_bin_number",
                                base_discretisation_n_bins=NBINS)
    df = res[0] if isinstance(res, list) else res
    return {c: float(df.iloc[0][c]) for c in df.columns if c.endswith(SUFFIX)}


def main():
    values = run()
    print("// mirp %s, recipe ih.ibsi_fbn (fixed bin number, %d bins), IBSI digital phantom"
          % (metadata.version("mirp"), NBINS))
    print("// generated by tests/vetting/oracles/gen_intensity_histogram_mirp.py")
    for column in sorted(MIRP_TO_NYXUS):
        key = column + SUFFIX
        if key not in values:
            print("// MISSING from this mirp build: %s" % key)
            continue
        print('    {"%s", %.17g},   // %s' % (MIRP_TO_NYXUS[column], values[key], column))
    print("\n// raw:", json.dumps(values, sort_keys=True))


if __name__ == "__main__":
    main()
