"""OFFLINE golden generator for tests/test_2d_glrlm_mirp.h (SPEC 6.4).

Runs MIRP GLRLM on the IBSI digital phantom and prints the golden table to paste into the oracle
test. Run offline; CI never invokes it - the reference tool is not a runtime dependency.

    conda create -n nyxus_mirp -c conda-forge python=3.11 mirp numpy
    python tests/vetting/oracles/gen_glrlm_mirp.py

Provenance to record at the pinned goldens: tool=mirp, version (printed by this script),
config=glrlm.ibsi_ng128, fixture=the IBSI phantom as tests/test_data.h stores it - read out of that
header by ibsi_phantom.phantom_slices(), so there is one copy of the phantom pixels and the
generators, the C++ tests and the tools all read it.

MIRP is the IBSI reference implementation; `2d_average` is the aggregation the Nyxus *_AVE features
implement (features computed per direction, then averaged).
"""
import json
import logging
from importlib import metadata

import numpy as np

# MIRP narrates its progress at INFO into the same stream as the golden table, and it configures its
# logger during the run, so the level has to be suppressed globally rather than set on a logger
logging.disable(logging.INFO)
import mirp   # noqa: E402  (import after logging is silenced)

from ibsi_phantom import phantom_slices   # noqa: E402

# MIRP feature column (before the aggregation suffix) -> the Nyxus feature it covers
MIRP_TO_NYXUS = {
    "rlm_sre":        "GLRLM_SRE",
    "rlm_lre":        "GLRLM_LRE",
    "rlm_lgre":       "GLRLM_LGLRE",
    "rlm_hgre":       "GLRLM_HGLRE",
    "rlm_srlge":      "GLRLM_SRLGLE",
    "rlm_srhge":      "GLRLM_SRHGLE",
    "rlm_lrlge":      "GLRLM_LRLGLE",
    "rlm_lrhge":      "GLRLM_LRHGLE",
    "rlm_glnu":       "GLRLM_GLN",
    "rlm_glnu_norm":  "GLRLM_GLNN",
    "rlm_rlnu":       "GLRLM_RLN",
    "rlm_rlnu_norm":  "GLRLM_RLNN",
    "rlm_r_perc":     "GLRLM_RP",
    "rlm_gl_var":     "GLRLM_GLV",
    "rlm_rl_var":     "GLRLM_RV",
    "rlm_rl_entr":    "GLRLM_RE",
}

SUFFIX = "_2d_avg"   # features averaged over the 4 in-slice directions


def run():
    slices = phantom_slices()
    volume = np.stack([a for a, _ in slices]).astype(float)
    mask = np.stack([m for _, m in slices])
    res = mirp.extract_features(image=volume, mask=mask, by_slice=True,
                                base_discretisation_method="none",   # the phantom is already discrete
                                glrlm_spatial_method="2d_average")
    df = res[0] if isinstance(res, list) else res
    return {c: float(df.iloc[0][c]) for c in df.columns if c.endswith(SUFFIX)}


def main():
    values = run()
    print("// mirp %s, recipe glrlm.ibsi_ng128 (by_slice + 2d_average + no discretisation),"
          " IBSI digital phantom" % metadata.version("mirp"))
    print("// generated by tests/vetting/oracles/gen_glrlm_mirp.py")
    for column in sorted(MIRP_TO_NYXUS):
        key = column + SUFFIX
        if key not in values:
            print("// MISSING from this mirp build: %s" % key)
            continue
        feature = MIRP_TO_NYXUS[column]
        for n in (feature, feature + "_AVE"):
            print('    {"%s", %.17g},   // %s' % (n, values[key], column))
    print("\n// raw:", json.dumps(values, sort_keys=True))


if __name__ == "__main__":
    main()
