"""OFFLINE golden generator for tests/test_2d_glrlm_pyradiomics.h (SPEC 6.4).

Runs PyRadiomics GLRLM on the IBSI digital phantom and prints the golden table to paste into the
oracle test. Run offline; CI never invokes it - the reference tool is not a runtime dependency.

    conda create -n nyxus_oracle -c conda-forge python=3.9 pyradiomics simpleitk numpy
    python tests/vetting/oracles/gen_glrlm_pyradiomics.py

Provenance to record at the pinned goldens: tool=pyradiomics, version (printed by this script),
config=glrlm.ibsi_ng128, fixture=the IBSI phantom as tests/test_data.h stores it.

The fixture is read out of tests/test_data.h rather than rebuilt here, so the generator and the C++
test cannot drift apart: there is one copy of the phantom pixels and both sides read it.

PyRadiomics reports one value per feature over the 4 in-slice directions, which is the Nyxus *_AVE
aggregation; averaging that over the 4 slices is the IBSI 2D-averaged aggregation the test uses.
"""
import json
import os
import re

import SimpleITK as sitk
import radiomics
from radiomics import glrlm

from ibsi_phantom import phantom_slices

# PyRadiomics feature name -> the Nyxus feature it covers
PYRADIOMICS_TO_NYXUS = {
    "ShortRunEmphasis":                 "GLRLM_SRE",
    "LongRunEmphasis":                  "GLRLM_LRE",
    "LowGrayLevelRunEmphasis":          "GLRLM_LGLRE",
    "HighGrayLevelRunEmphasis":         "GLRLM_HGLRE",
    "ShortRunLowGrayLevelEmphasis":     "GLRLM_SRLGLE",
    "ShortRunHighGrayLevelEmphasis":    "GLRLM_SRHGLE",
    "LongRunLowGrayLevelEmphasis":      "GLRLM_LRLGLE",
    "LongRunHighGrayLevelEmphasis":     "GLRLM_LRHGLE",
    "GrayLevelNonUniformity":           "GLRLM_GLN",
    "GrayLevelNonUniformityNormalized": "GLRLM_GLNN",
    "RunLengthNonUniformity":           "GLRLM_RLN",
    "RunLengthNonUniformityNormalized": "GLRLM_RLNN",
    "RunPercentage":                    "GLRLM_RP",
    "GrayLevelVariance":                "GLRLM_GLV",
    "RunVariance":                      "GLRLM_RV",
    "RunEntropy":                       "GLRLM_RE",
}

# binWidth=1 is identity on this integer phantom, so neither tool discretises
SETTINGS = dict(binWidth=1, distances=[1], force2D=True, force2Ddimension=0, weightingNorm=None,
                label=1, interpolator=None, resampledPixelSpacing=None)


def run():
    per_slice = []
    for a, m in phantom_slices():
        image, label = (sitk.GetImageFromArray(arr[None, :, :]) for arr in (a, m))
        for im in (image, label):
            im.SetSpacing((1.0, 1.0, 1.0))
        f = glrlm.RadiomicsGLRLM(image, label, **SETTINGS)
        f.enableAllFeatures()
        per_slice.append({k: float(v) for k, v in f.execute().items()})
    return {k: sum(s[k] for s in per_slice) / len(per_slice) for k in per_slice[0]}


def verify_pins(header, table, computed, tol=5e-3):
    """Compare EVERY golden pinned in `table` against this run.

    Checking a hand-picked subset is the failure mode this exists to avoid: it silently stops
    covering whatever is added to the table later. Anything the generator cannot produce is
    reported rather than skipped quietly. The tolerance is the loosest the test file asserts at,
    which is the log-based GLRLM_RE band.
    """
    text = re.sub(r"//[^\n]*", "", open(header, encoding="utf-8").read())
    body = text.split(table, 1)[1].split("{", 1)[1].split("};", 1)[0]
    ok, checked, unknown = True, 0, []
    for name, pinned in re.findall(r'\{\s*"(\w+)"\s*,\s*([-0-9.e+]+)\s*\}', body):
        if name not in computed:
            unknown.append(name)
            continue
        got, want = computed[name], float(pinned)
        if abs(got - want) > tol * max(1.0, abs(want), abs(got)):
            print("  FAIL %s: oracle=%r pinned=%s" % (name, got, pinned))
            ok = False
        checked += 1
    print("  verified %d pinned goldens against this run" % checked)
    if unknown:
        print("  not produced by this generator: %s" % ", ".join(sorted(unknown)))
        ok = False
    return ok


def main():
    values = run()
    print("// pyradiomics %s, recipe glrlm.ibsi_ng128, IBSI digital phantom (4 slices, averaged)"
          % radiomics.__version__)
    print("// generated by tests/vetting/oracles/gen_glrlm_pyradiomics.py")
    nyxus = {}
    for pyr_name in sorted(PYRADIOMICS_TO_NYXUS):
        if pyr_name not in values:
            print("// MISSING from this pyradiomics build: %s" % pyr_name)
            continue
        feature = PYRADIOMICS_TO_NYXUS[pyr_name]
        # the per-direction feature and its _AVE twin are the same quantity, and both names must
        # appear literally for the coverage report to credit them
        for n in (feature, feature + "_AVE"):
            nyxus[n] = values[pyr_name]
            print('    {"%s", %.17g},   // %s' % (n, values[pyr_name], pyr_name))
    print("\n// raw:", json.dumps(values, sort_keys=True))

    print("\n=== re-verify every pinned golden in test_2d_glrlm_pyradiomics.h ===")
    here = os.path.dirname(os.path.abspath(__file__))
    ok = verify_pins(os.path.join(here, "..", "..", "test_2d_glrlm_pyradiomics.h"),
                     "glrlm_2d_pyradiomics_ref_vals", nyxus)
    print("\n%s" % ("ALL CHECKS PASSED" if ok else "SOME CHECKS FAILED -- do not paste goldens"))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
