"""OFFLINE golden generator for tests/test_2d_glrlm_pyradiomics.h (SPEC 6.4).

Runs PyRadiomics GLRLM on the IBSI digital phantom and prints the golden table to paste into the
oracle test. Run offline; CI never invokes it - the reference tool is not a runtime dependency.

    conda create -n nyxus_oracle -c conda-forge python=3.9 pyradiomics simpleitk numpy
    python tests/vetting/oracles/gen_glrlm_pyradiomics.py

Provenance to record at the pinned goldens: tool=pyradiomics, version (printed by this script),
config=glrlm.ibsi_ng128, fixture=the IBSI phantom as tests/test_data.h stores it.

The fixture is read out of tests/test_data.h rather than rebuilt here, so the generator and the C++
test cannot drift apart: there is one copy of the phantom pixels and both sides read it.

PyRadiomics reports one value per feature over the 4 in-slice directions, which is the Nyxus *_AVE
aggregation; averaging that over the 4 slices is the IBSI 2D-averaged aggregation the test uses.
"""
import json

import SimpleITK as sitk
import radiomics
from radiomics import glrlm

from ibsi_phantom import phantom_slices

# PyRadiomics feature name -> the Nyxus feature it covers
PYRADIOMICS_TO_NYXUS = {
    "ShortRunEmphasis":                 "GLRLM_SRE",
    "LongRunEmphasis":                  "GLRLM_LRE",
    "LowGrayLevelRunEmphasis":          "GLRLM_LGLRE",
    "HighGrayLevelRunEmphasis":         "GLRLM_HGLRE",
    "ShortRunLowGrayLevelEmphasis":     "GLRLM_SRLGLE",
    "ShortRunHighGrayLevelEmphasis":    "GLRLM_SRHGLE",
    "LongRunLowGrayLevelEmphasis":      "GLRLM_LRLGLE",
    "LongRunHighGrayLevelEmphasis":     "GLRLM_LRHGLE",
    "GrayLevelNonUniformity":           "GLRLM_GLN",
    "GrayLevelNonUniformityNormalized": "GLRLM_GLNN",
    "RunLengthNonUniformity":           "GLRLM_RLN",
    "RunLengthNonUniformityNormalized": "GLRLM_RLNN",
    "RunPercentage":                    "GLRLM_RP",
    "GrayLevelVariance":                "GLRLM_GLV",
    "RunVariance":                      "GLRLM_RV",
    "RunEntropy":                       "GLRLM_RE",
}

# binWidth=1 is identity on this integer phantom, so neither tool discretises
SETTINGS = dict(binWidth=1, distances=[1], force2D=True, force2Ddimension=0, weightingNorm=None,
                label=1, interpolator=None, resampledPixelSpacing=None)


def run():
    per_slice = []
    for a, m in phantom_slices():
        image, label = (sitk.GetImageFromArray(arr[None, :, :]) for arr in (a, m))
        for im in (image, label):
            im.SetSpacing((1.0, 1.0, 1.0))
        f = glrlm.RadiomicsGLRLM(image, label, **SETTINGS)
        f.enableAllFeatures()
        per_slice.append({k: float(v) for k, v in f.execute().items()})
    return {k: sum(s[k] for s in per_slice) / len(per_slice) for k in per_slice[0]}


def main():
    values = run()
    print("// pyradiomics %s, recipe glrlm.ibsi_ng128, IBSI digital phantom (4 slices, averaged)"
          % radiomics.__version__)
    print("// generated by tests/vetting/oracles/gen_glrlm_pyradiomics.py")
    for pyr_name in sorted(PYRADIOMICS_TO_NYXUS):
        if pyr_name not in values:
            print("// MISSING from this pyradiomics build: %s" % pyr_name)
            continue
        feature = PYRADIOMICS_TO_NYXUS[pyr_name]
        # the per-direction feature and its _AVE twin are the same quantity, and both names must
        # appear literally for the coverage report to credit them
        for n in (feature, feature + "_AVE"):
            print('    {"%s", %.17g},   // %s' % (n, values[pyr_name], pyr_name))
    print("\n// raw:", json.dumps(values, sort_keys=True))


if __name__ == "__main__":
    main()
